# Generated by Django 5.1.1 on 2024-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='This is snippet', max_length=255),
        ),
    ]
